# Generated by Django 5.2.8 on 2026-03-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='featured_image',
            field=models.ImageField(max_length=255, upload_to='uploads/%Y/%m/%d'),
        ),
    ]
