# Generated by Django 5.2.8 on 2026-03-29 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_blog_featured_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blog',
            table='blog_blog',
        ),
        migrations.AlterModelTable(
            name='category',
            table='blog_category',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='blog_comment',
        ),
    ]
